### ISSUE TITLE
一点使用的问题

### ISSUE THREAD

**Issue by ScottXjw** [winter2048/PalServerTools#12]
1. 点击“立即更新”按钮会出现一个提示乱码
![image](https://github.com/winter2048/PalServerTools/assets/81411248/fca1d11e-16d1-45d9-8760-fb07f0c23258)
2. 如何才能调整游戏参数呢？ 我需要怎么设置

**Comment by winter2048** [comment]
> 1. 点击“立即更新”按钮会出现一个提示乱码
>    ![image](https://private-user-images.githubusercontent.com/81411248/308790141-fca1d11e-16d1-45d9-8760-fb07f0c23258.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxODQ3OTgsIm5iZiI6MTcwOTE4NDQ5OCwicGF0aCI6Ii84MTQxMTI0OC8zMDg3OTAxNDEtZmNhMWQxMWUtMTZkMS00NWQ5LTg3NjAtZmIwN2YwYzIzMjU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA1MjgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiYTEyNWZhMDI3MTIwNThmNGU0YzRiNGJkNWM0Y2U2MzU4OWMzYTViMDZkZjkxNDM5M2RiZmI5ODdlYzk3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H9ISzzYDLwoKnobIdHpeyEEx55Fg-QgMwNLw5766Bnc)
> 2. 如何才能调整游戏参数呢？ 我需要怎么设置

#1 使用更新功能需要将steamcmd的目录添加到系统的环境变量中。（仅支持steamcmd方式安装，steam客户端目前不支持）
#2 必须设置的参数：配置-基础配置-PalServer根目录，配置-服务器配置-管理员密码，配置-服务器配置-启用RCON。游戏参数在 配置-游戏参数调整 页面设置。

**Comment by ScottXjw** [comment]
非常感谢！

**Comment by winter2048** [comment]
关闭问题
