### ISSUE TITLE
启动报错，疑似打包问题?

### ISSUE THREAD

**Issue by hhzxxx** [winter2048/PalServerTools#14]
![image](https://github.com/winter2048/PalServerTools/assets/62325706/22bdcc4c-55ec-4822-8bc9-6dcf585ddbc6)
如图，我的电脑不存在这个路径。
2.0.8

**Comment by winter2048** [comment]
使用管理员打开cmd，执行 “lodctr /r” 命令试试。
https://www.cnblogs.com/ycdchina/p/10032406.html
