### ISSUE TITLE
咨询大佬一些问题

### ISSUE THREAD

**Issue by wifidofs1** [winter2048/PalServerTools#15]
1.SteamCMD未添加到系统环境变量中！一直提示这个 系统变量已添加，如图
![问题1](https://github.com/winter2048/PalServerTools/assets/142783505/ba077cc8-d357-4cc4-997a-29306a96ef04)
2.ini配置文件有的配置选项跟第三方生成INI文件的网站不一样
![问题2](https://github.com/winter2048/PalServerTools/assets/142783505/81f7e916-7a1e-43fc-bf51-b94c0bf44771)
3.可否发下您的私人联系方式到我邮箱：jiulingdianying@qq.com 方便后期添加优化需求， 不常登陆github

**Comment by wifidofs1** [comment]
还有一个问题，就是多开服，如何自定义面板端口，这边尝试修改了5000端口 启动后无法打开面板

**Comment by winter2048** [comment]
> 1.SteamCMD未添加到系统环境变量中！一直提示这个 系统变量已添加，如图 ![问题1](https://private-user-images.githubusercontent.com/142783505/309503755-ba077cc8-d357-4cc4-997a-29306a96ef04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjM0ODksIm5iZiI6MTcwOTQ2MzE4OSwicGF0aCI6Ii8xNDI3ODM1MDUvMzA5NTAzNzU1LWJhMDc3Y2M4LWQzNTctNGNjNC05OTdhLTI5MzA2YTk2ZWYwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxMDUzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWIxM2I1MGEzYWVkMGYyYmE3MWZkOThhNGNjZDkyNzcyYmZiNzA1NTk5ZTllNGRlMWI3ZDgxOWZlNzBiYzcyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.z_QWMPmhn63ONDZcl2aiSZC6EEfcIkgi9FguPBo-w6Y) 2.ini配置文件有的配置选项跟第三方生成INI文件的网站不一样 ![问题2](https://private-user-images.githubusercontent.com/142783505/309503811-81f7e916-7a1e-43fc-bf51-b94c0bf44771.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NjM0ODksIm5iZiI6MTcwOTQ2MzE4OSwicGF0aCI6Ii8xNDI3ODM1MDUvMzA5NTAzODExLTgxZjdlOTE2LTdhMWUtNDNmYy1iZjUxLWI5NGMwYmY0NDc3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwM1QxMDUzMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTViNzExYmZlMmMwOWVkZWYwNDQzNTQ3YTEzMzBhMDQ0ZTM4YWY3ODk0Mzc3YTc2MGFmMTM4NDQ1N2YzNTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1Et9C3kdVtoEFHjoKyrY4LE0MF3iAk0JwrY53cKQ0Fg) 3.可否发下您的私人联系方式到我邮箱：[jiulingdianying@qq.com](mailto:jiulingdianying@qq.com) 方便后期添加优化需求， 不常登陆github

1. 需要将steamcmd所在的文件夹添加到Path环境变量中，添加完成后在cmd中可以执行`steamcmd`命令则说明添加成功了。
![image](https://github.com/winter2048/PalServerTools/assets/31879147/eb489687-375e-48dd-846e-28a6218953df)

2. 是否可以提供下第三方生成配置的网站，在下个版本中会添加缺少的配置参数。

3. 可以联系 522112669@qq.com

4. 端口号修改无效确实是bug，目前暂时可以先使用环境变量来修改端口号，在cmd中先执行`set ASPNETCORE_URLS=http://*:5002`命令，然后再执行命令`PalServerTools.exe`运行工具。[预计下个版本修复]

感谢提交问题！

**Comment by wifidofs1** [comment]
默认的5000端口在哪儿改？

**Comment by wifidofs1** [comment]
现在运行2.0.9后提示升级2.0.9.1 一直升级不生成，CMD窗口闪退

**Comment by winter2048** [comment]
https://github.com/winter2048/PalServerTools/blob/f7397d5b84d4ba882e9090f6bb1b4bdf9d3ad0c3/src/PalServerTools/appsettings.json#L2
在根目录下的appsettings.json文件里，修改ASPNETCORE_URLS属性。例如："ASPNETCORE_URLS": "http://0.0.0.0:5005"

**Comment by winter2048** [comment]
> 现在运行2.0.9后提示升级2.0.9.1 一直升级不生成，CMD窗口闪退

v2.0.9已经是最新版，是否有提示的截图？

**Comment by wifidofs1** [comment]
新版本在D盘创建了2个目录后，在根目录下的appsettings.json文件里，修改ASPNETCORE_URLS属性。例如："ASPNETCORE_URLS": "http://0.0.0.0:5005/" 
包括这个json里面的程序目录后，同时打开exe  只能识别一个游戏进程 无法实现多开

**Comment by wifidofs1** [comment]
appsettings.json  " PalServerPath": "D:\\pal\\plServer_bin\\palworld_server",  这里设置的是2个客户端目录

**Comment by winter2048** [comment]
> 新版本在D盘创建了2个目录后，在根目录下的appsettings.json文件里，修改ASPNETCORE_URLS属性。例如："ASPNETCORE_URLS": "http://0.0.0.0:5005/" 包括这个json里面的程序目录后，同时打开exe 只能识别一个游戏进程 无法实现多开

https://github.com/winter2048/PalServerTools?tab=readme-ov-file#%E5%A4%9A%E5%BC%80%E5%8A%9F%E8%83%BD
请尝试更新到v2.0.15版本，新版本添加了多开的支持。
