### ISSUE TITLE
没有发现安装包里面有exe的可执行文件啊

### ISSUE THREAD

**Issue by yutao7777** [winter2048/PalServerTools#2]

**Comment by winter2048** [comment]
https://github.com/winter2048/PalServerTools/releases

**Comment by TinyNiceMan** [comment]
为什么打开exe后弹了一下cmd窗口就闪退了

**Comment by winter2048** [comment]
先安装ASP.NET Core 6.0 https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-aspnetcore-6.0.26-windows-x64-installer，按说明的步骤来。

**Comment by TinyNiceMan** [comment]
按步骤来的 是不是windows2012不支持？能否远程下

**Comment by rainbow2man** [comment]
一样的问题，只能猜配置文件的参数是什么意思来一个一个试。但是还是没成功。b站倒是有个拿你代码二开的可以用

**Comment by winter2048** [comment]
> 一样的问题，只能猜配置文件的参数是什么意思来一个一个试。但是还是没成功。b站倒是有个拿你代码二开的用

运行无需手动修改配置文件，所以参数都可以在运行后的工具里配置。感谢测试，建议贴出失败/报错的截图，方便分析原因。

**Comment by winter2048** [comment]
> 按步骤来的 是不是windows2012不支持？能否远程下

目前只在win10/win11上测试过，其它系统没有试过。

**Comment by aa342138039** [comment]
安装了[ASP.NET Core 6.0]还是闪退

**Comment by winter2048** [comment]
> 安装了[ASP.NET Core 6.0]还是闪退

还需同时安装.net 6.0运行时，文档里漏掉了……
https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-6.0.26-windows-x64-installer

**Comment by rainbow2man** [comment]
> > 安装了[ASP.NET Core 6.0]还是闪退
> 
> 还需同时安装.net 6.0运行时，文档里漏掉了…… https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-6.0.26-windows-x64-installer

666解决! star了捏

**Comment by winter2048** [comment]
添加自动安装脚本：https://github.com/winter2048/PalServerTools/blob/master/README.md

欢迎提交bug或提交希望新增的功能！
