### ISSUE TITLE
启动提示错误 could not parse the json file

### ISSUE THREAD

**Issue by dayuya** [winter2048/PalServerTools#34]
![image](https://github.com/user-attachments/assets/b75f8a4d-ddd7-432d-bc0d-17d99b874160)

**Comment by HaitaoJin** [comment]
appsetting.json文件内容不正确，请提供appsetting.json文件的内容。

**Comment by dayuya** [comment]
你好这是我的   appsetting.json
![image](https://github.com/user-attachments/assets/189f7140-b6f2-41bb-a5f8-e09233cc8816)

**Comment by HaitaoJin** [comment]
`将路径的"\"改成"\\"，在josn中，路径不能使用"\"`

**Comment by dayuya** [comment]
好了 已解决 谢谢你
